Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    number_of_flats = len(Flat)
                      ^^^^^^^^^
TypeError: object of type 'ModelBase' has no len()
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    number_of_flats = Flat.objects.annotate(num_flats=Count('butas')).filter(num_flats__gt=0).count()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1090, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'butas' into field. Choices are: flat_nr, gyventojas, id, kaupiamasis_inasas, owner, owner_id, size_kv
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    number_of_flats = Flat.objects.annotate(num_flats=Count('butas')).filter(num_flats__gt=0).count()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1090, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'butas' into field. Choices are: flat_nr, gyventojas, id, kaupiamasis_inasas, owner, owner_id, size_kv
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    number_of_flats = Flat.objects.annotate(num_flats=Count('flat')).filter(num_flats__gt=0).count()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1090, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'flat' into field. Choices are: flat_nr, gyventojas, id, kaupiamasis_inasas, owner, owner_id, size_kv
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    number_of_flats = Flat.objects.annotate(num_flats=Count('Flat')).filter(num_flats__gt=0).count()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1090, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'Flat' into field. Choices are: flat_nr, gyventojas, id, kaupiamasis_inasas, owner, owner_id, size_kv
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    number_of_flats = Flat.objects.annotate(num_flats=Count('Flat')).filter(num_flats__gt=0).count()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1090, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'Flat' into field. Choices are: flat_nr, gyventojas, id, kaupiamasis_inasas, owner, owner_id, size_kv
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    number_of_flats = Flat.objects.annotate(num_flats=Count('Flat')).filter(num_flats__gt=0).count()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1090, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'Flat' into field. Choices are: flat_nr, gyventojas, id, kaupiamasis_inasas, owner, owner_id, size_kv
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    number_of_flats = Flat.objects.annotate(num_flats=Count('Flat')).filter(num_flats__gt=0).count()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1090, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'Flat' into field. Choices are: flat_nr, gyventojas, id, kaupiamasis_inasas, owner, owner_id, size_kv
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 13, in index
    total_inasas = sum(kaupiamasis_inasas for kaupiamasis_inasas in kaupiamasis_inasas_objects)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'int' and 'Kaupiamasis_Inasas'
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 13, in index
    kaupiamasis_inasas_objects = Kaupiamasis_Inasas.objects.filter(flat__in=flats)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1533, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1383, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1193, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'flat' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 13, in index
    kaupiamasis_inasas_objects = Kaupiamasis_Inasas.objects.filter(Flat__in=flats)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1533, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1383, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1193, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'flat' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 13, in index
    kaupiamasis_inasas_objects = Kaupiamasis_Inasas.objects.filter(Flat__in=flats)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1533, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1383, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1193, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'Flat' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 16, in index
    total_inasas = kaupiamasis_inasas_objects.aggregate(total=Sum('size'))['total'] or 0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\query.py", line 592, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 393, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\aggregates.py", line 64, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 942, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1933, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1780, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\db\models\sql\query.py", line 1681, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'size' into field. Choices are: flat_owner, flat_owner_id, id, payment_rate
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    total_wages = staff.aggregate(total_wages=Sum('wage'))['total'] or 0
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'total'
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    total_wages = staff.aggregate(total_wages=Sum('wage'))['total'] or 0
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'total'
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    total_wages = staff.aggregate(total_wages=Sum('wage'))['isviso'] or 0
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'total'
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    total_wages = staff.aggregate(total_wages=Sum('wage'))['isviso'] or 0
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'isviso'
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    total_wages = staff.aggregate(total_wages=Sum('wage'))['total'] or 0
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'total'
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    total_wages = staff.aggregate(total_wages=Sum('wage'))['total'] or 0
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'total'
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    total_wages = staff.aggregate(total_wages=Sum('wage'))['total'] or 0
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'total'
Internal Server Error: /administracija/
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py", line 31, in index
    total_wages = staff.aggregate(total_wages=Sum('wage'))['total'] or 0
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'total'
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 141, in handle_token
    raise template.TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'static' takes at least one argument (path to file)
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /img/fonas.jpg
Not Found: /img/fonas.jpg
Not Found: /img/fonas.jpg
Not Found: /img/fonas.jpg
Not Found: /img/fonas.jpg
Not Found: /img/fonas.jpg
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 19, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''css/style.css' from ''css/style.css'
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /favicon.ico
Not Found: /butas.jpg
Not Found: /butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Watching for file changes with StatReloader
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /flat/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /accounts/login/media/img/butas.jpg
Not Found: /accounts/login/media/img/butas.jpg
Not Found: /accounts/login/media/img/butas.jpg
Not Found: /accounts/login/media/img/butas.jpg
Not Found: /accounts/login/media/img/butas.jpg
Not Found: /flat/media/img/butas.jpg
Not Found: /resident/media/img/butas.jpg
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /styles.css
Not Found: /favicon.ico
Not Found: /styles.css
Not Found: /css/styles.css
Not Found: /css/styles.css
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\Bendrija\gyventojas\views.py", line 20, in index
    return render(request, 'index.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Edga\PycharmProjects\Test\venv\Lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?
C:\Users\Edga\PycharmProjects\Test\Bendrija\administracija\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\Edga\PycharmProjects\Test\Bendrija\Bendrija\settings.py changed, reloading.
Watching for file changes with StatReloader
